Hw2 trie
AmarskiyArtem/secondSemester pull request #4
Opened 2023-03-10 09:12 UTC by AmarskiyArtem

2023-03-13 11:34 UTC, yurii-litvinov requested changes

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Program.cs
> +Trie trie = new Trie();
```suggestion
var trie = new Trie();
```
Не пишите без крайней нужды один тип дважды.

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Program.cs
> +                Console.WriteLine(trie.HowManyStartsWithPrefix(prefix) + " words with that prefix");
```suggestion
                Console.WriteLine($"{trie.HowManyStartsWithPrefix(prefix)} words with that prefix");
```
Интерполяция строк более прогрессивна.

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +            this.IsTerminate = false;
Это не нужно, значение по умолчанию для булевых полей и так false

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +            this.children = new Dictionary<char, TrieNode>();
Это можно было вынести в инициализатор поля и конструктор удалить.

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +        public Dictionary<char, TrieNode> children;
public-полей быть не должно, тем более что IsTerminate у Вас свойство.

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +    }
Тут тоже конструктор не нужен

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +        }
И никто не удаляет вершины, которые, возможно, больше не нужны. Так на самом деле можно, но это надо обосновать. Что Вы хотите приобрести, пожертвовав оперативкой?

2023-03-13 11:34 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +    }
Это не укладывается в O(|prefix|), требуемый в условии

2023-03-13 15:42 UTC, AmarskiyArtem commented on homeworks/hw2/Trie/Trie.cs
> +        }
Простота добавления новых элементов (возможно префиксы в каком-то виде совпадут) + если удалять лишние вершины, то придется проверять, нет ли у них потомков, у которых выполняется isTerminated, т.е либо жертвуем оперативкой, либо усложняем структуру данных

2023-03-15 09:06 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +        }
Проверять ничего не стоит, если в каждой вершине помнить, сколько "через неё проходит" хранимых строк. А вот соображение про простоту добавления новых элементов принято — жертвуете оперативкой, чтобы уменьшить количество вызовов сборщика мусора, тем самым выигрывая в скорости работы (а поскольку сборка мусора — дорогая операция, выигрыш может быть очень существенным, и если априори известно, что добавляться/удаляться будут похожие строки, то Ваш подход вполне осмысленный).

2023-03-15 09:10 UTC, yurii-litvinov approved these changes
В целом ок. Зачтена.

2023-03-15 09:10 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Program.cs
> +var trie = new Trie();
Я после `}` ставлю пустую строку, но дело вкуса

2023-03-15 09:10 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +        public Dictionary<char, TrieNode>? Children { get; set; } = new Dictionary<char, TrieNode>();
Зачем Dictionary nullable? Он в конструкторе инициализируется не null-ом, и дальше вряд ли есть потребность его занулять.

И можно сделать
```suggestion
        public Dictionary<char, TrieNode>? Children { get; set; } = new();
```

2023-03-15 09:10 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +    private readonly TrieNode root = new TrieNode();
```suggestion
    private readonly TrieNode root = new();
```

2023-03-15 09:10 UTC, yurii-litvinov commented on homeworks/hw2/Trie/Trie.cs
> +    }
```suggestion
        return true;
    }
```

2023-03-15 12:37 UTC, merged